context:
  version: 0.75.0

package:
  name: fsautocomplete
  version: ${{ version }}

source:
  git: https://github.com/fsharp/fsautocomplete
  tag: v${{ version }}

build:
  number: 1
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fsautocomplete --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: F# language server using Language Server Protocol
  homepage: https://github.com/fsharp/fsautocomplete

extra:
  recipe-maintainers:
    - danielnachun
