context:
  version: "0.85.0"

package:
  name: fsautocomplete
  version: ${{ version }}

source:
  - git: https://github.com/fsharp/fsautocomplete
    tag: v${{ version }}
    target_directory: git
  - url: https://github.com/ionide/FsAutoComplete/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ac1ded37dd38b63035ea38a76175988f30010e22f0600c2f9bd5809126e8a724

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fsautocomplete --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - git/license-files/
  summary: F# language server using Language Server Protocol
  homepage: https://github.com/fsharp/fsautocomplete

extra:
  recipe-maintainers:
    - danielnachun
